/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjektG2;

import oru.inf.InfDB;

/**
 *
 * @author andre
 */
public class Anvandare extends javax.swing.JFrame {

   
    private InfDB db;
    public Anvandare(InfDB db) {
        initComponents();
        this.db = db;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        mPane = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Välkommen till lärarplattformen för informatik");

        mPane.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mPane.setRequestFocusEnabled(false);

        jMenu1.setText("Start");
        jMenu1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mPane.add(jMenu1);

        jMenu2.setText("Blogg");
        jMenu2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mPane.add(jMenu2);

        jMenu5.setText("Profil");
        jMenu5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mPane.add(jMenu5);

        jMenu4.setText("Logga ut");
        jMenu4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mPane.add(jMenu4);

        setJMenuBar(mPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar mPane;
    // End of variables declaration//GEN-END:variables
}
